In [14]:
from sympy import LeviCivita, symbols
import numpy as np

# Define the Levi-Civita symbol using NumPy and list comprehension
eps = np.array([[[float(LeviCivita(i, j, k)) for k in range(3)] for j in range(3)] for i in range(3)])
print("Levi-Civita symbol:")
print(eps)

# Define the vectors A and B
A = np.array([1, 2, 3])
B = np.array([4, -5, 6])

# Calculate the cross product using the Levi-Civita symbol
cross_product = np.array([sum(eps[i, j, k] * A[j] * B[k] for j in range(3) for k in range(3)) for i in range(3)])

# Print the result
print("Cross product of A and B:")
print(cross_product)

Levi-Civita symbol:
[[[ 0.  0.  0.]
  [ 0.  0.  1.]
  [ 0. -1.  0.]]

 [[ 0.  0. -1.]
  [ 0.  0.  0.]
  [ 1.  0.  0.]]

 [[ 0.  1.  0.]
  [-1.  0.  0.]
  [ 0.  0.  0.]]]
Cross product of A and B:
[ 27.   6. -13.]


In [1]:
from sympy import LeviCivita, symbols
import numpy as np

# Define the Levi-Civita symbol using NumPy list comprehension
eps = np.array([[[float(LeviCivita(i, j, k)) for k in range(3)] for j in range(3)] for i in range(3)])

# Define the components of the vectors A and B
A1, A2, A3 = symbols('A1 A2 A3')
B1, B2, B3 = symbols('B1 B2 B3')

A = np.array([A1, A2, A3])
B = np.array([B1, B2, B3])

# Calculate the cross product using the Levi-Civita symbol
cross_product = np.array([
    sum(eps[i, j, k] * A[j] * B[k] for j in range(3) for k in range(3))
    for i in range(3)
])

# Print the cross product
print(cross_product)

[1.0*A2*B3 - 1.0*A3*B2 -1.0*A1*B3 + 1.0*A3*B1 1.0*A1*B2 - 1.0*A2*B1]
